name: GitHub Actions Demo

on: [push]

jobs:
  Execute-Python-Script:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupérer le code de ton dépôt dans le runner
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Installer et configurer Python sur la machine virtuelle
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Lancer ton fichier Python
      - name: Run Python script
        run: python job.py
